name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Clone cc-extra-expressions-pack
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update; sudo apt install zip
        
      - name: Create EX2 archives
        run: |
          zip -q -r cc-extra-expressions-pack.ccmod ./*
          tar -czf cc-extra-expressions-pack.tar.gz --transform 's,^,cc-extra-expressions-pack/,' ./*
          
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        
      - name: Create release
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} -t "CCED ${{ steps.get_version.outputs.VERSION }}" ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES: cc-extra-expressions-pack.ccmod cc-extra-expressions-pack.tar.gz
